version: '2'

services:
  proxy:
    build: .
    command: bash -c "ls -a && make && ./proxy"
    volumes:
      - "./src:/src"
      - "./logs:/var/log/erss"
    ports:
      - "12345:12345"
    tty: true